### ISSUE TITLE
Does this facilitate C - Go communication?

### ISSUE THREAD

**Issue by OliverEvans96** [tylertreat/chan#27]
Hi,

Looks like a great package! I imagine that the primary use case is go-like channels *within a C program*, but I'm wondering - have you actually mirrored the Go datastructure exactly? Is it possible to use CGO to embed a C program using this library inside of Go and actually send and receive on the same channel from both languages?

Thanks!
Oliver

**Comment by tylertreat** [comment]
> have you actually mirrored the Go datastructure exactly? Is it possible to use CGO to embed a C program using this library inside of Go and actually send and receive on the same channel from both languages?

No, unfortunately this isn't possible nor is it the intention of this package. This is just an implementation of the Go channel API in C. It doesn't interop. Would be a neat idea though!

**Comment by OliverEvans96** [comment]
@tylertreat - do you have any idea what would be required to do interop?

**Comment by tylertreat** [comment]
I'm not entirely sure, but this might give you an idea: https://github.com/matiasinsaurralde/cgo-channels

**Comment by OliverEvans96** [comment]
Thanks a lot!
